http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.x.x

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
#http:
#  base_url: xxxx.com
#  ssl_certificate: /ssl/fullchain.pem
#  ssl_key: /ssl/privkey.pem
#  ip_ban_enabled: true
#  login_attempts_threshold: 5
